//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vector.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vector.UI.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the first vector..
        /// </summary>
        internal static string Input_Vector_First {
            get {
                return ResourceManager.GetString("Input.Vector.First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the second vector..
        /// </summary>
        internal static string Input_Vector_Second {
            get {
                return ResourceManager.GetString("Input.Vector.Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinate X of a vector:.
        /// </summary>
        internal static string Input_Vector_X {
            get {
                return ResourceManager.GetString("Input.Vector.X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinate Y of a vector:.
        /// </summary>
        internal static string Input_Vector_Y {
            get {
                return ResourceManager.GetString("Input.Vector.Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinate Z of a vector:.
        /// </summary>
        internal static string Input_Vector_Z {
            get {
                return ResourceManager.GetString("Input.Vector.Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick up the menu:.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Add vector..
        /// </summary>
        internal static string Menu_1 {
            get {
                return ResourceManager.GetString("Menu.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Subtract vector..
        /// </summary>
        internal static string Menu_2 {
            get {
                return ResourceManager.GetString("Menu.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coordinate inputed incorrect!.
        /// </summary>
        internal static string Message_IncorrectInput {
            get {
                return ResourceManager.GetString("Message.IncorrectInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no that punkt!.
        /// </summary>
        internal static string Message_IncorrectPunkt {
            get {
                return ResourceManager.GetString("Message.IncorrectPunkt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result of the operation: Vector=.
        /// </summary>
        internal static string Output_Result {
            get {
                return ResourceManager.GetString("Output.Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VECTRO APPLICATION.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
